### ISSUE TITLE
OAuth Flows Design and Impl

### ISSUE THREAD

**Issue by chirino** [syndesisio/syndesis-project#12]
Document the oauth flow impl.  Implement backend and front end bits so it works with Salesforce and Twitter.

OAuth overall feature proposal
Twitter OAuth Flow
* Which libraries and bits of information are involved (13)
* Back-end impl (13, 14)
* UXD (13)
* UI (14)

Salesforce OAuth Flow
* Which libraries and bits of information are involved (13)
* Back-end impl (13, 14)
* UXD (13)
* UI (14)

Client ID/Secret management
* UXD (13)
* UI (14)
* Back-end store (13)

Connections using OAuth-based security
* Runtime (14)

**Comment by gashcrumb** [comment]
@chirino Why not just continue the discussion on the epics?

@sjcox-rh @dongniwang I think for this one we'd just have a button in place of the current token/secret fields, question is would we want the button to do a full re-direct to the target app (twitter/salesforce) for the OAuth flow or use a popup.  Popup means we can save state much easier, otherwise we'll need to figure out how to cache the UI's current state.

Caching UI state wouldn't be too difficult, for example I could write that to local storage and put a key in the redirect URL which the app could use to reload it's state.

**Comment by zregvart** [comment]
I think it makes sense to have a discussion here. Do you think that the course [I outlined for credentials](https://github.com/zregvart/syndesis-project/blob/2387c823249ec0e652329d32a5242c7e2cadceeb/design-proposals/003-credentials.md) makes sense here or do we need to go into another direction?

**Comment by rhuss** [comment]
I added some comments to #11 which actually boil down to that at the moment I can't see the big benefit of having credentials (aka tokens) to be stored in separate entities from the `connection` in it's `configuredProperties` (as we do now). I believe the relation connection:token is always 1:1.

**Comment by jimmidyson** [comment]
I agree with @rhuss, I think it makes more sense right now to have the credentials part of the Connection as configuredProperties like they are now, just sourced from the oauth flow rather than provided by the user. That is the least impact on existing work too. If we need to separate out credentials then we can do so later imo.

**Comment by jludvice** [comment]
At some point of creation oauth connection user must create OAuth App in target system (like twitter or salesforce) and provide callback url back to syndesis, right ?
We can't do oauth dance without app credentials with callback url pointing to back to syndesis instance.

How does the creation of oauth app fit to citizen developer workflow?

Another point -> integration testing of those oauth flows will be really painfull because the oauth app callback url keeps changing (each deployed syndesis has different url `syndesis-${namespace}.wherever.com`

**Comment by rhuss** [comment]
@jludvice there is a story #13 for this kind of configuration in order to add application id and secret. This is independent from a concrete OAuth authentication flow for a connections (referenced here). 

The app id and secret need to be obtained by the 'expert' developer role separately from the backend system and entered in this global configuration section. Neverthess we need to give the expert user a hint what he has to use as callback URL for the app.
