### ISSUE TITLE
Tech extension upload in UI

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis-project#122]

**Comment by rhuss** [comment]
UX Story: https://github.com/syndesisio/syndesis-ux/issues/44

**Comment by nicolaferraro** [comment]
From the UX story, I see that list/view/delete are covered by #123, while this issue should be about the tech extension "creation".

The story says that users will set name & description. But it should not be possible to create a tech extension without the binary artifact. So I guess also the artifact should be uploaded.

But if we add the binary artifact to the set of uploaded fields, what's the purpose of name and description? They are already contained in the binary metadata.

I'm sure I'm missing something here...

@gashcrumb, @rhuss, @lburgazzoli

**Comment by gashcrumb** [comment]
@nicolaferraro I believe we kinda decided on the call that `name` and `description` would only come from the metadata and wouldn't be set or edited by the user at all.

**Comment by nicolaferraro** [comment]
Makes sense..

**Comment by nicolaferraro** [comment]
@gashcrumb how should it be a rest interface for uploading the extension from UI?
Since everything is stored in metadata, I think that a service that accepts a binary archive and returns the extension object would be sufficient (similar to what has been discussed [in the issue about the metadata format](https://github.com/syndesisio/syndesis-project/issues/120)).

I was thinking to using the classic "multipart form" method for the binary file. Are there better alternatives?

**Comment by gashcrumb** [comment]
Yeah, that sounds good.  I'd definitely say yes, return the extension object that's created, also note there's an event service that the UI subscribes to for receiving change events, creating a new extension should also trigger that event service.

I think multipart form should be good for now, we can always make it more fancy if needed.
