### ISSUE TITLE
Poor error message with an incorrect callback URL on a Salesforce component

### ISSUE THREAD

**Issue by sjavurek** [syndesisio/syndesis-project#129]
I accidentally fat fingered my callback URI. When I tested my SalesForce connection, a new screen popped up with:

error=redirect_uri_mismatch&error_description=redirect_uri%20must%20match%20configuration

It's not the most user friendly message I have ever seen. :-) Something like, please check your callback URL in your Salesforce configuration or something similar may be a bit more direct.

**Comment by gashcrumb** [comment]
Unfortunately we may not have control over this, I think the page shown when you hit this comes from salesforce

**Comment by rhuss** [comment]
Exactly, there is nothing we can do about ;-(

It's really a salesforce page (you can see this on your browser URL) and I suspect, that since setting up Salesforce Apps is usually not an end-user task (and only a one-shot thing which then can't get wrong anymore if setup correctly), they might think this error page is good enough. However, setting up an and using an OAuth flow is both part of _our_ end-user experience (which is very likely not a use case that Salesforce thought about).

@zregvart you as our oauth expert, is this a valid description ? Or do you see any possibility to avoid this Salesforce error page ?

**Comment by zregvart** [comment]
> @zregvart you as our oauth expert, is this a valid description ? Or do you see any possibility to avoid this Salesforce error page ?

I have found no way we can convince Salesforce to redirect back or show a meaningful error page. And without access there is no way for us to check the setup on Salesforce without asking the user for username/password (which we do not want).
