### ISSUE TITLE
Global settings / setup / configuration

### ISSUE THREAD

**Issue by chirino** [syndesisio/syndesis-project#13]
Should handle things like:

* Client ID/Secret management
* Github setup
* OpenShift Namespace settings.

**Comment by rhuss** [comment]
@chirino Do you mean a dedicated UI page with associated backend storage which is global to the installation (i.e. independent to an integration). Is there are corresponding JIRA issue ? (just asking to provide a link)

**Comment by rhuss** [comment]
We should first collect all possible global configurations here. What comes to mind first are all parameters which we currently add now during the instantiation of the OpenShift templates:

* GitHub oauth client id
* GitHub oauth secret

Then there is configuration global to connectors which are used for _every_ connection created by the connector. It is a subset of the configuration properties exposed by a connector. The global params need to be marked in the connector metadata somehow as 'global' so that it could be picked up the setup UI (e.g. like the client id if the connector used an OAuth workflow). 

The global configuration needs to be stored in the backend and used in the Setup UI page but also when creating a connection (where the config properties are copied over to the connection ?). Also changing a connector related property needs to update the configuredProperty in already existing. connections.

**Comment by rhuss** [comment]
@chirino wdym with OpenShift namespace settings ?

**Comment by chirino** [comment]
@rhuss the name space the we deploy intetgrations into.  Right now we deploy into the same namespace that syndesis runs in, but in theory the user might want to deploy into a different namespace.  

To be honest, they might want to deploy into a whole different openshift cluster and namespace.  Not sure how hard it would be to d this one since setting up remote openshift client connections might be a bit tricky.

**Comment by jludvice** [comment]
Hi @rhuss @dongniwang @gashcrumb , did we cover Create connection page  and possible changes related to this issue?
Currently we have `clientId` and `clientSecret`  in both create connection and settings page.
Should create connection page somehow consume informations from settings page?
Or do we just delete those fields from create connection ui and magically append them in the backend?
What happens when user wants to create twitter connection but it's not configured in settings?

![settings-connection.png](https://images.zenhubusercontent.com/5939117e51aa2c305780da73/f7276fd4-e489-4dc8-a5a0-04dd8bbf524c)

**Comment by zregvart** [comment]
> Currently we have clientId and clientSecret in both create connection and settings page.

Yes, the UI with the OAuth dance is not here yet.

> Should create connection page somehow consume informations from settings page?

It should, but the create connection page for OAuth capable connectors (Salesforce, Twitter) should have only one button _Connect to ..._

> Or do we just delete those fields from create connection ui and magically append them in the backend?

See above, the goal is to have a single button.

> What happens when user wants to create twitter connection but it's not configured in settings?

I think we discussed this, but I'm not sure what we concluded, either that the unconfigured connector won't be present when you try to create connection, or there will be a message saying that it needs configuring...

See https://github.com/sjcox-rh/syndesis-ux/blob/28682d1c0cb54928d8e2a7e1147cad86fa026b2c/designs/oauth/oauth.md

**Comment by dongniwang** [comment]
@jludvice There's a new design for the Create a Connection flow. Please see the PR for OAuth flow in the ux repo syndesisio/syndesis-ux/pull/16/.

**Comment by chirino** [comment]
rest/ui note: configuration properties now have a tags:["oauth-client-id"] field.  The UI could use this to detect which connection properties should not be displayed.  Current only the 'oauth-client-id' and 'oauth-client-secret' tags exist.  We should likely do the same for the auth token and secret properties too.

**Comment by chirino** [comment]
Closing issue out as this is in place.
