### ISSUE TITLE
Exceeding OpenShift quotas handling and explaining to citizen integrator

### ISSUE THREAD

**Issue by dsimansk** [syndesisio/syndesis-project#156]
My comment on Lifecycle handling issue #22:
> ... after a while of using resource constrained project on Online cluster. I think we need a way to gather exceeding events from OpenShift and report them back to user in a simple && meaningful way.
E.g. permanent warning banner similar to OS console, that quota is exceeded etc.

Brake-down:
- Show a warning that limit is closing
  - Inform user that he has only 1 Integration left to deploy etc. 
  - Check available resources before another Integrations is allowed to be published. To prevent situation when available limit is too small
- Show permanent warning that limit is reached
  - Inform user that limit of deployments is reached and with explanation
  - Don't allow any more publishing, just drafting.

 

OpenShift banner example:
![screen shot 2017-10-30 at 13 45 47](https://user-images.githubusercontent.com/5637792/32171519-ae5d291a-bd78-11e7-8097-8aca1a9e3915.png)

**Comment by dsimansk** [comment]
@amysueg FYI I've tried to summarize&expand my comment from Lifecycle issue.

**Comment by amysueg** [comment]
thanks for these examples and details, @dsimansk

**Comment by amysueg** [comment]
@catrobson Can you point me to existing designs or additional examples from OpenShift that we could leverage for iPaaS for this type of notification?

**Comment by catrobson** [comment]
You can find some designs around this type of information here:  
https://redhat.invisionapp.com/share/QED5XSUJX . <-- overall resources being used in OpenShift - probably too detailed for a business user
https://redhat.invisionapp.com/share/YSDL0KRKW#/screens/260758518 . <-- In context warnings that they are hitting the limit when looking at their applications/deployments
https://redhat.invisionapp.com/share/PMDCE3G94#/251857784_Wiz_-_Available_1 <-- A flow showing warning a user when they are trying to add more content and it will exceed their space limits (prevention)

**Comment by amysueg** [comment]
@sjcox-rh @dongniwang and I talked this through. For the two scenarios, @dsimansk describes above, two different approaches are recommended.

Broadly, messages and their presentations are classified by severity and context. 

For warnings, we recommend using the Patternfly Toast Notification: http://www.patternfly.org/pattern-library/communication/toast-notifications/

For severe, permanent, or global issues, use a modal dialog (similar to the last recommendation by @catrobson in the previous comment). When the user *must* take action in order to proceed, the Patternfly modal is preferred for attention-getting:
http://www.patternfly.org/pattern-library/widgets/#modal

For status notifications in context, the Patternfly Inline Message is recommended: http://www.patternfly.org/pattern-library/communication/inline-notifications/

**Comment by chirino** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  chirino@gmail.com
    Domain hiramchirino.com has exceeded the max emails per hour (162/150 (108%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from out-7.smtp.github.com ([192.30.252.198]:33517)
	by host313.hostmonster.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.89_1)
	(envelope-from <noreply@github.com>)
	id 1f0Nmf-0013Z6-0S
	for hiram@hiramchirino.com; Mon, 26 Mar 2018 02:47:17 -0600
Date: Mon, 26 Mar 2018 01:47:04 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1522054024;
	bh=PxhL9TlPc8UpRyFW9oo+NNCBPQa3QQ8sRyZX8wihMHQ=;
	h=Date:From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=JjczQdHpJuttEjibdtT/b04SM86CdDJiPCJ9XeL0TfFWDHfxuVoJyXQUqJJxyntTh
	 c5fZ8yq/FWaudN870eLcD/bympfa3kgyWXNh7fbhqVOtMQclo7bGG+NU79s6tnP7JG
	 Yp5duO+lThw0gf8QVugyfSNfRPbTbunvyj93BnrI=
