### ISSUE TITLE
User should be able to logout

### ISSUE THREAD

**Issue by chirino** [syndesisio/syndesis-project#43]
Right now the logout link in the UI does nothing.

**Comment by chirino** [comment]
@rhuss @kcbabo does this need to get resolved for TP ?

**Comment by kcbabo** [comment]
How much work is it?  Aesthetically, I think it feels pretty weird to not be able to logout.  In environments with shared browsers, it could be a security problem as well.

**Comment by rhuss** [comment]
I'm still about to understand our own SSO flow via keycloak, but @jimmidyson knows best what todo to invalidate a token.

**Comment by jimmidyson** [comment]
Right now, log in is automatic: as soon as a user hits Syndesis in their browser they are forced through the OAuth flow via Keycloak. If they have already authorised Syndesis against OpenShift and GitHub then it will appear to be seamless authenication, no need to enter any info or log in again as it is reusing the previous authorization. In this case, logging out will kinda do nothing as the user will then just be forced through the (transparent) oauth login flow again and be logged in, albeit with a new token, which of course the user knows nothing about.

If you really want to be able to logout, then we would need to introduce a landing/login page that the user is redirected to after logout, as well as on first visit. Even then, clicking on the login button will still kick off a transparent oauth flow through the OpenShift and GitHub providers... This is pretty standard when using third party providers for authentication. As an example, if you use Travis/CircleCI and login via GitHub then you see this same flow when you return, or if you log in to a site via Facebook/Google the same thing happens.

**Comment by rhuss** [comment]
I agree with @jimmidyson that the modern auth flow is that you get automatically connected when accessing an app, even when new tokens get generated. We do it in github all the time.

Logout feels really a bit old school here, so I wonder whether we should not simply remove the "logout" button.

**Comment by kcbabo** [comment]
I'm struggling to think of a web-based service that I use today that does not provide logout capability.

**Comment by dsimansk** [comment]
@jimmidyson @rhuss this logout landing page could be just a simple page with message to re-enter console `click here`. 

There is already [an issue ](https://github.com/syndesisio/syndesis-ui/issues/255) about landing page anyway, with a nice preview design.
 
There also nothing fancy about Openshift logout page itself. Ours would look a bit nicer thanks to Rachel :)
![screen shot 2017-06-26 at 13 42 30](https://user-images.githubusercontent.com/5637792/27537730-5a805f12-5a75-11e7-9bf9-f59e82773ee8.png)

**Comment by jimmidyson** [comment]
@dsimansk We should absolutely copy the OpenShift console logout flow so we're as consistent as possible. Note that clicking on `console` in the screenshot above will automatically log you in, as long as the cluster is configured to use a third party oauth provider, as our rh-idev cluster is (using GitHub). So logout is a bit of an odd flow, but agree that we should have the same flow.

**Comment by kahboom** [comment]
I kind of agree with all of the differing arguments here. Overall, though, if we do offer a logout feature (transparent as it may be), it does feel weird that OpenShift's console makes it so that the user navigates back to the dashboard or landing page they are automatically logged back in. That feels frustrating as hell and not really like a "logout" at all. We'd essentially be having "logout" just to give the user a mental sense of being logged out, because when they go back to the dashboard soon after they might be like.. wait, what?

I didn't implement the user login component in the UI, so I may be missing something. I don't see why we can't improve the user experience using just authentication, but it sounds like it won't be consistent with OpenShift's console (no idea). When the user logs out we would:
- Obviously stop requesting refresh tokens.
- We delete a GH personal access token that we have manually generated for them on login/authorization/whatever you want.
- Haven't checked if we have one yet, but we'd then reset the `authenticated` and `authenticatedUser` flags if they exist (if they don't, we should probably create one), which should depend on the localStorage-stored GitHub authentication credentials. I'd go as far as to say we should store old, stale personal access tokens in localStorage.
- In the code we already check for existing session token, but if there is none (if it's `null`, which it should be if they log out) AND there is no personal access token / GH credentials in localStorage--and this is different from us currently checking if it's the first IDP with `syndesis-first-idp` see [here](https://github.com/syndesisio/syndesis-ui/blob/master/src/app/app.module.ts#L88)--then we send them to the GH/OpenShift login flow again (which wouldn't require the re-authorization part). I am assuming this is possible considering the cluster will still be in tact.

A bit of a hassle, but I _think_ it's possible if we really want the ability to truly logout without spontaneously combusting the cluster and requiring reauthorization each time. Again, not a professional with KC and didn't implement the auth component, so feel free to correct me.

@dsimansk - Wow, that was a while back, when I was more in tune with things haha. Surprised you dug that up. And no problem! Do we have an issue open for that already, btw? If not, I'll open one specifically for the logout. I remember there being some limitations to how much we can modify the OpenShift login/logout UI, but I'll dig up some old emails and copy/paste the discussion on that issue.

**Comment by kcbabo** [comment]
I'm not too concerned about OpenShift Dedicated behavior at this point.  I have a free account for OpenShift Online.  It has a logout button.  When I press it, I'm logged out and have to enter my credentials again.  This is the experience that our users will be accustomed to.  Shouldn't we be consistent with that?

**Comment by rhuss** [comment]
Actually it depends on the authentication provider we use (which btw is also a question for TP):

* If we use an own authentication provider to store user accounts like OpenShift online does one can simply require a new login each time. It's a configuration option of the authentication provider.
* When we use GitHub as authentication provider, then removing the relevant (persistent) GitHub cookie would not only log out from Syndesis but then also from GitHub itself, which might be quite unexpected and undesirable. 

Are we planning to use GitHub as authentication provider for production or do we use OpenShift Online ?

**Comment by jimmidyson** [comment]
As we're just targeting Online it would be great to be able to share the same Keycloak as Online as well as using the same strategy that openshift.io uses to auth to GitHub too.

**Comment by rhuss** [comment]
@jimmidyson does those mean we could get rid of our own Keycloak instance for TP1 ? That would be awesome. Should I open an issue for exploring the way to use a central Keycloak (which we then would swich to OpenShift Online's one for TP1)

**Comment by jimmidyson** [comment]
It's a possibility and should be the target for GA SaaS.

**Comment by rhuss** [comment]
Also somewhat related: If a user's token is invalid in the UI (e.g. because of a server restart), then the UI should return to the landing page. Actually, all sort of weird behaviour is happening.

**Comment by chirino** [comment]
@jimmidyson so the openshift logout flow is also broken right (from the PoV that you can get back in without providing credentials)?
I'd rather not say we have logout option if it's not going to work properly.

**Comment by chirino** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  chirino@gmail.com
    Domain hiramchirino.com has exceeded the max emails per hour (170/150 (113%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from out-5.smtp.github.com ([192.30.252.196]:42733)
	by host313.hostmonster.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.89_1)
	(envelope-from <noreply@github.com>)
	id 1f0Nmk-0013dn-BH
	for hiram@hiramchirino.com; Mon, 26 Mar 2018 02:47:22 -0600
Date: Mon, 26 Mar 2018 01:47:11 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1522054031;
	bh=G4ZldJhI5LIBX9huRGyzJuKCG2oHUbDHW5MhbwtLQKI=;
	h=Date:From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=QVe1Lnnx9ndt/aCprRhtLJ2xCNM0U6RIhJo+lWEHovy3YJyFOtFcr11AJsC8PrpKR
	 4IUa7Q/n+g4QuJtuMAMJBu/lvUiF7tWdvofsy95pHo/fgNNfmae4a2UNzymLaLxN8p
	 jzRfo5dyCfsva4kdD28wCAR90oK1BvzHazESodig=
